export const galleryImages = [
  // 관리자가 승인한 정적 이미지는 assets/gallery에 파일을 넣고 이 목록에 추가하면 공개됩니다.
  // 예: { src: "assets/gallery/example.webp", title: "이미지 제목", description: "이미지 설명", observationPoints: [], exampleTitles: [] }
  {
    id: "photo-001",
    imageKey: "0",
    src: "assets/gallery/01-cat-smoke.png",
    webpSrc: "assets/gallery/webp/01-cat-smoke.webp",
    title: "빛과 먼지 사이로 손을 뻗은 고양이",
    description: "창가의 빛과 공기 중 먼지가 겹치며 고양이의 움직임이 무대처럼 보이는 사진입니다. 장면의 몽환적인 분위기와 고양이의 호기심을 함께 살리면 좋은 제목을 만들 수 있습니다.",
    alt: "햇빛과 연기처럼 보이는 먼지 사이로 앞발을 뻗는 고양이",
    prompt: "빛, 먼지, 앞발의 방향을 단서로 삼아 고양이가 무엇을 잡으려는지 상상해보세요.",
    observationPoints: ["창문에서 들어오는 강한 역광", "연기처럼 퍼지는 먼지의 결", "몸을 길게 세운 고양이의 집중한 자세"],
    exampleTitles: ["오늘의 사냥감은 햇빛", "먼지를 붙잡는 방법", "창가 마법 수업"],
    isUserUpload: false,
  },
  {
    id: "photo-003",
    imageKey: "2",
    src: "assets/gallery/03-alligators.jpeg",
    webpSrc: "assets/gallery/webp/03-alligators.webp",
    title: "나란히 쉬는 악어들의 낮은 시선",
    description: "여러 악어가 같은 방향을 바라보며 몸을 겹쳐 쉬고 있는 장면입니다. 표정이 크게 드러나지 않아도 배열, 눈높이, 질감을 이용하면 긴장감 있는 제목을 만들 수 있습니다.",
    alt: "뿌리와 흙 위에 여러 악어가 겹쳐 쉬고 있는 모습",
    prompt: "비슷한 자세로 모인 악어들의 시선과 표정을 회의나 대기 상황처럼 바꿔 생각해보세요.",
    observationPoints: ["한 방향을 향한 여러 개의 눈", "거친 피부와 나무뿌리의 질감", "가까운 거리에서 느껴지는 긴장감"],
    exampleTitles: ["습지 회의 시작 전", "누가 먼저 움직일까", "조용한 압박 면접"],
    isUserUpload: false,
  },
  {
    id: "photo-004",
    imageKey: "3",
    src: "assets/gallery/04-field-portrait.jpg",
    webpSrc: "assets/gallery/webp/04-field-portrait.webp",
    title: "흐린 들판을 걸어오는 검은 옷의 인물",
    description: "넓은 하늘과 낮은 지평선, 어두운 옷의 인물이 대비되는 사진입니다. 공간의 여백이 크기 때문에 감정의 온도와 거리감을 제목에 담기 좋습니다.",
    alt: "흐린 하늘 아래 풀밭을 걸어오는 검은 옷의 인물",
    prompt: "넓은 빈 하늘과 작은 인물 사이의 거리감을 제목의 핵심 감정으로 잡아보세요.",
    observationPoints: ["화면 대부분을 차지하는 흐린 하늘", "검은 옷과 들판의 색 대비", "정면으로 걸어오는 느린 움직임"],
    exampleTitles: ["하늘이 먼저 도착한 날", "말수가 적은 들판", "혼자 걷는 오후"],
    isUserUpload: false,
  },
  {
    id: "photo-007",
    imageKey: "6",
    src: "assets/gallery/07-puppy-oh-hi.jpg",
    webpSrc: "assets/gallery/webp/07-puppy-oh-hi.webp",
    title: "카메라 가까이 다가온 웃는 강아지",
    description: "강아지의 얼굴이 화면 중앙을 가득 채우고 배경은 흐릿하게 밀려난 사진입니다. 직접 말을 거는 느낌, 첫 만남의 밝은 에너지를 제목으로 표현하기 좋습니다.",
    alt: "노란 테두리 안에서 카메라를 향해 웃는 강아지",
    prompt: "가까운 얼굴과 밝은 표정을 살려 짧은 인사말이나 등장 장면처럼 제목을 만들어보세요.",
    observationPoints: ["렌즈 가까이 다가온 코와 눈", "입을 벌린 밝은 표정", "노란 테두리가 만든 사진 속 사진 효과"],
    exampleTitles: ["처음 뵙겠습니다, 간식 있나요", "친해지는 속도 2초", "오늘의 햇살 담당"],
    isUserUpload: false,
  },
  {
    id: "photo-008",
    imageKey: "7",
    src: "assets/gallery/08-convenience-store.jpg",
    webpSrc: "assets/gallery/webp/08-convenience-store.webp",
    title: "냉장고 문 사이로 물을 고르는 순간",
    description: "한 손에는 음료를 들고 다른 손으로 생수를 고르는 장면입니다. 일상적인 선택이지만 유리문, 시선, 손의 위치가 작은 이야기의 시작점이 됩니다.",
    alt: "편의점 냉장고 문을 열고 큰 생수병을 집는 사람",
    prompt: "평범한 구매 장면을 가장 진지한 선택의 순간처럼 바꿔보세요.",
    observationPoints: ["열린 냉장고 문과 반사된 얼굴", "이미 손에 든 음료와 새로 고르는 생수", "옆사람의 어깨가 만든 관찰자 시점"],
    exampleTitles: ["수분 보충의 갈림길", "이미 골랐지만 다시 고른다", "편의점 앞 중대한 결정"],
    isUserUpload: false,
  },
  {
    id: "photo-009",
    imageKey: "8",
    src: "assets/gallery/09-reggae-singer.jpg",
    webpSrc: "assets/gallery/webp/09-reggae-singer.webp",
    title: "노란 조명 아래 노래하는 무대 위 가수",
    description: "강한 무대 조명과 마이크를 잡은 손, 크게 열린 입이 공연의 에너지를 전달합니다. 소리의 크기와 조명의 색을 제목 안에서 함께 느끼게 만드는 연습에 좋습니다.",
    alt: "노란 무대 조명 아래 마이크를 잡고 노래하는 가수",
    prompt: "사진에 들리지 않는 소리를 제목으로 떠올려보세요. 조명 색과 표정이 좋은 단서입니다.",
    observationPoints: ["노란색으로 가득한 무대 조명", "마이크에 가까이 붙은 얼굴", "손과 표정에서 느껴지는 힘"],
    exampleTitles: ["조명이 먼저 따라 부른 밤", "목소리가 노랗게 번졌다", "마이크와의 거리 0센티"],
    isUserUpload: false,
  },
  {
    id: "photo-010",
    imageKey: "9",
    src: "assets/gallery/10-sparkler.jpg",
    webpSrc: "assets/gallery/webp/10-sparkler.webp",
    title: "손끝에서 타오르는 작은 불꽃",
    description: "초점은 불꽃에 맞고 인물은 흐릿하게 배경으로 물러난 사진입니다. 짧게 타오르는 순간, 손의 위치, 어두운 배경을 이용해 감성적인 제목을 만들 수 있습니다.",
    alt: "손에 든 스파클러가 어두운 배경 앞에서 빛나는 장면",
    prompt: "짧게 사라지는 불꽃의 시간감을 제목에 담아보세요.",
    observationPoints: ["선명한 불꽃과 흐릿한 얼굴의 대비", "어두운 배경에 남는 작은 빛", "손끝에 집중된 화면 구성"],
    exampleTitles: ["사라지기 전 가장 밝은 말", "손끝의 작은 여름", "밤이 잠깐 웃은 순간"],
    isUserUpload: false,
  },
  {
    id: "subject-1",
    imageKey: "10",
    src: "assets/gallery/Subject1.jpg",
    title: "눈가에 눈물이 맺힌 노인의 얼굴",
    description: "가까운 얼굴 사진에서 주름, 눈가의 물기, 아래로 향한 시선이 감정의 밀도를 만듭니다. 직접적인 판단보다 오래 머문 표정의 결을 제목으로 다듬기 좋은 이미지입니다.",
    alt: "눈가에 눈물이 맺힌 노인이 아래를 바라보는 클로즈업",
    prompt: "표정의 이유를 단정하지 말고, 눈빛과 주름이 남기는 감정만 짧게 붙잡아보세요.",
    observationPoints: ["눈가에 맺힌 작은 눈물", "깊게 잡힌 이마와 눈가의 주름", "정면이 아닌 아래로 향한 시선"],
    exampleTitles: ["말보다 먼저 고인 것", "오래된 오후의 얼굴", "삼킨 문장의 무게"],
    isUserUpload: false,
  },
  {
    id: "subject-2",
    imageKey: "11",
    src: "assets/gallery/Subject2.png",
    title: "개구리 조각상 앞에 모인 사람들",
    description: "붉은 제복의 사람들이 개구리 조각상 앞에서 예를 갖추고, 주변 사람들은 놀란 표정으로 바라보는 익살스러운 장면입니다. 중앙 사물과 주변 반응의 차이를 제목으로 살리기 좋습니다.",
    alt: "붉은 제복을 입은 사람들이 개구리 조각상 앞에 모이고 주변 사람들이 놀라는 장면",
    prompt: "주인공처럼 앉아 있는 개구리와 주변 사람들의 과한 반응을 대비시켜보세요.",
    observationPoints: ["중앙에 앉은 개구리 조각상", "붉은 제복을 입은 사람들의 공손한 자세", "뒤쪽 관람객들의 놀란 표정"],
    exampleTitles: ["오늘의 의전 대상", "개구리 회장님 입장", "예상보다 엄숙한 행사"],
    isUserUpload: false,
  },
  {
    id: "subject-3",
    imageKey: "12",
    src: "assets/gallery/Subject3.png",
    title: "거대한 무가 날아오는 만화풍 추격 장면",
    description: "속도선, 말풍선, 놀란 표정이 한눈에 들어오는 만화풍 이미지입니다. 과장된 크기와 빠른 움직임을 이용해 짧고 강한 제목을 만들 수 있습니다.",
    alt: "만화풍 배경에서 거대한 무가 날아오고 두 인물이 놀라 달아나는 장면",
    prompt: "무의 크기, 속도선, 말풍선의 반응을 이용해 황당한 위기 제목을 붙여보세요.",
    observationPoints: ["화면을 가로지르는 거대한 무", "속도를 강조하는 파란 선", "상반된 두 인물의 표정과 대사"],
    exampleTitles: ["채소계 최종 보스", "반찬이 아니라 재난", "오늘의 급식은 추격전"],
    isUserUpload: false,
  },
  {
    id: "subject-4",
    imageKey: "13",
    src: "assets/gallery/Subject4.png",
    title: "카메라 속 개구리 사진을 함께 보는 사람들",
    description: "카메라 화면 속 사진을 보며 여러 사람이 동시에 웃는 장면입니다. 사진 안의 사진 구조와 사람들의 표정이 제목의 단서가 됩니다.",
    alt: "아이들과 사진가가 카메라 화면 속 웃는 개구리 사진을 보며 웃는 장면",
    prompt: "카메라 화면 안의 작은 사진과 바깥 사람들의 웃음이 어떻게 연결되는지 제목으로 표현해보세요.",
    observationPoints: ["카메라 화면에 보이는 작은 개구리 사진", "한곳으로 모인 사람들의 시선", "웃음이 번지는 얼굴들"],
    exampleTitles: ["웃음이 저장되었습니다", "오늘의 모델은 화면 안에", "사진 확인 시간 1초 만에 합격"],
    isUserUpload: false,
  },
  {
    id: "subject-5",
    imageKey: "14",
    src: "assets/gallery/Subject5.png",
    title: "진료실 구석에서 팔짱 낀 아기와 난감한 의사",
    description: "작은 아기가 정장을 입고 팔짱을 낀 채 서 있고, 의사는 얼굴을 감싸고 있습니다. 크기와 태도의 반전이 강해 짧은 대사형 제목을 만들기 좋습니다.",
    alt: "진료실에서 정장을 입은 아기가 팔짱을 끼고 서 있고 의사가 고개를 숙인 장면",
    prompt: "아기의 작은 몸과 어른스러운 자세가 만드는 반전을 제목의 중심으로 잡아보세요.",
    observationPoints: ["팔짱을 낀 아기의 단호한 자세", "얼굴을 감싼 의사의 난감한 몸짓", "옆에 있는 눈을 가린 조각상"],
    exampleTitles: ["담당의 호출하겠습니다", "오늘 진료는 제가 봅니다", "작지만 결재권 있음"],
    isUserUpload: false,
  },
  {
    id: "subject-6",
    imageKey: "15",
    src: "assets/gallery/Subject6.png",
    title: "개구리 심사위원 앞에서 걷는 붉은 제복들",
    description: "무대 위 패션 쇼처럼 보이는 장면에서 개구리 캐릭터가 10점 팻말을 들고 있습니다. 심사, 자세, 무대 조명이라는 단서를 묶어 유머러스한 제목을 만들 수 있습니다.",
    alt: "무대에서 붉은 제복을 입은 사람들이 걷고 개구리 심사위원이 10점 팻말을 든 장면",
    prompt: "심사위원처럼 앉은 개구리와 런웨이 분위기를 연결해보세요.",
    observationPoints: ["10점 팻말을 든 개구리", "줄지어 걷는 붉은 제복의 사람들", "무대 조명과 심사표 소품"],
    exampleTitles: ["자세 점수 만점", "개구리의 냉정한 10점", "런웨이를 지배한 심사위원"],
    isUserUpload: false,
  },
  {
    id: "subject-7",
    imageKey: "16",
    src: "assets/gallery/Subject7.png",
    title: "사라진 감자튀김 앞에서 우는 조각상과 남자",
    description: "눈물을 폭포처럼 흘리는 조각상, 함께 우는 인물, 바닥의 감자튀김 하나가 과장된 비극을 만듭니다. 사소한 원인과 큰 반응의 대비가 제목 포인트입니다.",
    alt: "감자튀김 하나가 떨어진 테이블 앞에서 조각상과 남자가 크게 우는 만화풍 장면",
    prompt: "아주 작은 사건을 세상 끝난 일처럼 표현하는 과장법을 써보세요.",
    observationPoints: ["폭포처럼 쏟아지는 눈물", "테이블 위에 남은 감자튀김 하나", "말풍선과 안내판이 알려주는 사건의 단서"],
    exampleTitles: ["감자튀김 하나의 장례식", "소스보다 짠 눈물", "잃어버린 한 조각의 시대"],
    isUserUpload: false,
  },
  {
    id: "subject-9",
    imageKey: "18",
    src: "assets/gallery/Subject9.png",
    title: "군복 입은 아기 교관과 의자에 앉은 개구리",
    description: "군사 훈련장처럼 꾸며진 공간에서 아기가 막대를 들고 설명하고, 개구리는 편하게 앉아 있습니다. 엄숙한 배경과 작은 교관의 반전이 유머를 만듭니다.",
    alt: "군복을 입은 아기가 지도 위에서 막대를 들고 설명하고 개구리가 의자에 앉은 장면",
    prompt: "엄숙한 훈련장과 작은 교관의 크기 차이를 제목의 반전으로 사용해보세요.",
    observationPoints: ["테이블 위에 선 작은 교관", "뒤쪽 벽의 해골 표시와 훈련 문구", "느긋하게 앉아 있는 개구리"],
    exampleTitles: ["오늘 교관님은 기저귀 사이즈", "멘붕 대비 특별 훈련", "작전명 낮잠 금지"],
    isUserUpload: false,
  },
  {
    id: "subject-10",
    imageKey: "19",
    src: "assets/gallery/Subject10.png",
    title: "사무실 복도를 질주하는 금붕어 배달원",
    description: "금붕어 얼굴을 한 정장 차림 인물이 작은 스쿠터를 타고 복도를 달리는 초현실적인 장면입니다. 사무실의 딱딱함과 엉뚱한 속도감을 연결하면 재미있는 제목이 됩니다.",
    alt: "어항 같은 헬멧을 쓴 금붕어 얼굴의 정장 인물이 빨간 스쿠터를 타고 사무실 복도를 달리는 장면",
    prompt: "사무실 복도라는 익숙한 공간에 갑자기 등장한 속도감을 제목으로 잡아보세요.",
    observationPoints: ["금붕어 얼굴과 둥근 투명 헬멧", "빨간 스쿠터와 휘날리는 넥타이", "무심히 지나가는 사무실 사람들"],
    exampleTitles: ["5분 안에 회의실 도착", "물 밖의 긴급 결재", "복도 주행 금지 구역"],
    isUserUpload: false,
  },
  {
    id: "subject-11",
    imageKey: "20",
    src: "assets/gallery/Subject11.png",
    title: "찜질방에서 휴대폰을 보는 고양이",
    description: "수건을 두른 고양이가 오이팩을 하고 누워 스마트폰을 보고 있습니다. 휴식 공간과 디지털 몰입의 대비가 명확해 생활형 유머 제목에 어울립니다.",
    alt: "찜질방에서 수건을 두르고 오이팩을 한 고양이가 누워 휴대폰을 보는 장면",
    prompt: "편안해야 할 휴식 시간에 휴대폰을 놓지 못하는 모습을 제목으로 표현해보세요.",
    observationPoints: ["눈 위의 오이팩과 수건", "배 위에 놓인 담요와 손에 든 휴대폰", "뒤쪽 찜질방 분위기와 음식 소품"],
    exampleTitles: ["힐링 중 알림 확인", "찜질방도 와이파이가 중요해", "오이팩 아래 실시간 검색"],
    isUserUpload: false,
  },
  {
    id: "subject-12",
    imageKey: "21",
    src: "assets/gallery/Subject12.png",
    title: "편의점 컵라면 코너에서 장보는 알파카",
    description: "밤의 편의점에서 알파카가 장바구니를 들고 컵라면 진열대를 바라보는 장면입니다. 익숙한 쇼핑 동작과 낯선 주인공의 조합이 제목의 재미를 만듭니다.",
    alt: "편의점 컵라면 진열대 앞에서 장바구니를 든 알파카가 상품을 고르는 장면",
    prompt: "컵라면을 고르는 평범한 순간을 알파카의 취향 고민으로 바꿔보세요.",
    observationPoints: ["한 줄 가득 놓인 컵라면 진열대", "장바구니를 든 알파카의 앞발", "밤 편의점의 밝은 조명"],
    exampleTitles: ["야식 취향이 복슬복슬", "알파카의 매운맛 상담", "장바구니가 말한 오늘의 기분"],
    isUserUpload: false,
  },
  {
    id: "imm-012",
    imageKey: "33",
    src: "assets/gallery/offended-cat.jpg",
    title: "주방 조리대 위, 서운함이 가득한 고양이",
    description: "조리대 위에 앉은 고양이가 눈을 가늘게 뜨고 귀를 살짝 젖힌 채 카메라를 바라보는 사진입니다. 표정에서 묘하게 서운함이 읽혀, 사람의 대사처럼 바꾸면 짧고 재미있는 제목을 만들 수 있습니다.",
    alt: "주방 조리대 위에서 눈을 가늘게 뜨고 서운한 표정을 짓는 주황색 고양이",
    prompt: "가늘게 뜬 눈과 젖힌 귀를 단서로, 고양이가 방금 무슨 일을 겪었는지 한 문장 대사로 상상해보세요.",
    observationPoints: ["가늘게 뜬 눈과 살짝 젖힌 귀", "정면을 향한 서운한 듯한 시선", "조리대 위로 들어온 부드러운 자연광"],
    exampleTitles: ["간식 약속, 안 지켰지", "나 방금 다 봤어", "오늘부터 말 안 해"],
    isUserUpload: false,
  },
  {
    id: "imm-013",
    imageKey: "23",
    src: "assets/gallery/24-funny-red-polo.jpg",
    title: "빨간 셔츠를 입고 곁눈질로 웃는 남자",
    description: "회색 칠판 같은 배경 앞에서 한 남자가 시선을 옆으로 흘리며 입꼬리를 올린 사진입니다. 표정을 사실로 단정하기보다 곁눈질과 참는 듯한 미소가 만드는 장난스러운 분위기를 살리면 좋은 제목을 만들 수 있습니다.",
    alt: "회색 칠판 배경 앞에서 빨간 폴로 셔츠를 입고 옆을 곁눈질하며 웃는 남자",
    prompt: "옆으로 새는 시선과 참는 듯한 미소를 한 문장 속마음처럼 바꿔보세요.",
    observationPoints: ["옆으로 흘긋 향한 곁눈질", "입꼬리만 올린 참는 듯한 미소", "선명한 빨간 셔츠와 회색 배경의 대비"],
    exampleTitles: ["나 부른 거 다 들었어", "안 웃으려고 했는데", "방금 그 농담 말이지"],
    isUserUpload: false,
  },
  {
    id: "imm-014",
    imageKey: "24",
    src: "assets/gallery/suit-tiny-desk-gimbap.png",
    title: "유치원 작은 의자에 앉아 김밥을 먹는 정장 청년",
    description: "어린이집 교실의 작은 책상과 의자에 정장을 입은 청년이 몸을 접고 앉아 김밥을 먹는 사진입니다. 큰 사람과 작은 가구의 크기 대비, 진지한 옷차림과 소박한 김밥의 어긋남을 제목의 중심으로 잡으면 좋습니다.",
    alt: "어린이집 교실의 노란 작은 책상과 의자에 정장을 입은 청년이 앉아 김밥을 집어 먹는 모습",
    prompt: "어른의 정장과 아이용 가구가 만드는 크기 차이를 한 장면의 상황극처럼 상상해보세요.",
    observationPoints: ["몸에 비해 한참 작은 노란 책상과 의자", "각 잡힌 검은 정장과 넥타이", "책상 위에 놓인 김밥 한 줄"],
    exampleTitles: ["첫 출근, 자리 배정 완료", "점심시간은 평등하다", "오늘부터 이 반 담임입니다"],
    isUserUpload: false,
  },
  {
    id: "imm-015",
    imageKey: "25",
    src: "assets/gallery/pigeon-steals-fry.png",
    title: "감자튀김을 채 가는 비둘기와 놀란 남자",
    description: "야외 식당에서 한 남자가 입을 벌린 사이, 비둘기가 감자튀김 하나를 물고 날아오르는 순간을 잡은 사진입니다. 음식을 가운데 두고 사람과 새의 시선·동작이 부딪치는 찰나를 짧고 재미있게 표현하기 좋습니다.",
    alt: "야외 식당 테이블에서 남자가 입을 벌리고 놀라는 사이 비둘기가 감자튀김을 물고 날아오르는 장면",
    prompt: "사람과 새의 동작이 겹치는 찰나를 한 문장 대사로 바꿔보세요.",
    observationPoints: ["감자튀김을 문 채 날개를 편 비둘기", "크게 벌어진 남자의 입과 눈", "접시 위에 남은 햄버거와 감자튀김"],
    exampleTitles: ["그건 내 거였는데", "기습은 위에서 온다", "점심값 두 명분"],
    isUserUpload: false,
  },
  {
    id: "imm-016",
    imageKey: "26",
    src: "assets/gallery/suit-bathtub-newspaper.png",
    title: "옷을 입은 채 욕조에 앉아 신문을 읽는 남자",
    description: "물 없는 욕조 안에 정장을 입은 남자가 신발까지 신은 채 앉아 신문을 펼친 사진입니다. 장소와 행동이 어긋나는 상황을 침착한 태도와 묶어 능청스러운 제목으로 풀면 어울립니다.",
    alt: "타일 욕실의 욕조 안에 정장과 구두 차림으로 앉아 신문을 펼쳐 읽는 남자",
    prompt: "엉뚱한 장소에서 너무 태연한 태도의 간극을 제목의 웃음 포인트로 잡아보세요.",
    observationPoints: ["옷과 구두를 갖춘 채 욕조에 앉은 자세", "양손으로 펼친 신문", "물기 없는 마른 욕조와 샤워 커튼"],
    exampleTitles: ["여기가 제일 조용해서요", "오늘자 욕조 라운지", "방해 금지 구역"],
    isUserUpload: false,
  },
  {
    id: "imm-017",
    imageKey: "27",
    src: "assets/gallery/shocked-home-selfie.png",
    title: "두 손으로 볼을 감싸고 크게 놀란 표정의 여성",
    description: "거실에서 한 여성이 양손으로 볼을 감싸고 입을 크게 벌려 과장되게 놀라는 표정의 셀카입니다. 표정의 강도와 정면 구도를 그대로 살려 짧고 강한 한마디 제목을 붙이는 연습에 좋습니다.",
    alt: "집 거실에서 양손으로 볼을 감싸고 입을 크게 벌린 채 눈을 크게 뜬 여성의 셀카",
    prompt: "과장된 표정 하나만으로 어떤 소식을 들은 순간인지 상상해 제목으로 옮겨보세요.",
    observationPoints: ["볼을 감싼 두 손", "크게 벌어진 입과 치켜뜬 눈썹", "정면을 가득 채운 얼굴 구도"],
    exampleTitles: ["설마 진짜야?", "방금 뭐라고 했어", "이번 달 카드값"],
    isUserUpload: false,
  },
  {
    id: "imm-018",
    imageKey: "28",
    src: "assets/gallery/laptop-in-shopping-cart.png",
    title: "마트 카트 안에 앉아 노트북으로 일하는 남자",
    description: "채소 코너 앞에서 정장을 입은 남자가 쇼핑 카트 안에 들어가 앉아 무릎에 노트북을 올리고 일하는 사진입니다. 일상 공간과 업무 자세의 어긋남을 살리면 직장인의 피로를 담은 제목을 만들기 좋습니다.",
    alt: "마트 채소 코너 앞에서 정장을 입은 남자가 쇼핑 카트 안에 앉아 노트북을 무릎에 올리고 작업하는 모습",
    prompt: "장소만 마트일 뿐 자세는 사무실인 이 간극을 한 문장으로 정리해보세요.",
    observationPoints: ["카트 안에 들어가 앉은 자세", "무릎 위에 펼친 노트북", "뒤로 늘어선 채소 진열대"],
    exampleTitles: ["재택의 끝은 어디인가", "장 보다가 회의 잡힘", "여기도 와이파이 됩니다"],
    isUserUpload: false,
  },
  {
    id: "imm-019",
    imageKey: "29",
    src: "assets/gallery/cookbook-in-shower.png",
    title: "샤워 부스 안에 서서 요리책을 읽는 남자",
    description: "유리 샤워 부스 안에 셔츠와 넥타이 차림의 남자가 서서 두꺼운 요리책을 펼쳐 읽는 사진입니다. 장소와 행동이 맞지 않는 상황을 무표정한 태도와 함께 담담한 제목으로 풀면 어울립니다.",
    alt: "유리 샤워 부스 안에 셔츠와 넥타이 차림으로 서서 요리책을 펼쳐 읽는 남자",
    prompt: "엉뚱한 칸에 들어가 평범한 일을 하는 사람의 사정을 한 문장으로 짐작해보세요.",
    observationPoints: ["좁은 샤워 부스 안에 선 자세", "두 손으로 펼친 요리책", "셔츠·넥타이와 젖지 않은 욕실"],
    exampleTitles: ["여기서만 집중이 돼요", "오늘 저녁 메뉴 연구 중", "한 칸짜리 서재"],
    isUserUpload: false,
  },
  {
    id: "imm-020",
    imageKey: "30",
    src: "assets/gallery/cat-steals-pizza.png",
    title: "피자를 낚아채 가는 고양이와 놀란 남자",
    description: "소파에 앉은 남자가 입을 벌린 사이, 고양이가 몸을 날려 피자 조각을 채 가는 순간을 흔들린 화면으로 잡은 사진입니다. 빠른 움직임과 놀란 표정이 겹치는 찰나를 짧고 재미있는 제목으로 옮기기 좋습니다.",
    alt: "거실 소파에서 남자가 입을 벌리고 놀라는 사이 고양이가 피자 조각을 물어 채 가는 흔들린 순간",
    prompt: "흔들린 화면이 만드는 속도감을 그대로 살려 사건의 순간을 제목으로 잡아보세요.",
    observationPoints: ["피자로 몸을 날린 고양이의 잔상", "크게 벌어진 남자의 입", "흔들려 번진 거실 배경"],
    exampleTitles: ["선빵은 고양이가", "내 피자 어디 갔어", "민첩성 만렙"],
    isUserUpload: false,
  },
  {
    id: "imm-021",
    imageKey: "31",
    src: "assets/gallery/title-academy-cat-student.png",
    webpSrc: "assets/gallery/webp/title-academy-cat-student.webp",
    title: "교실 책상 앞에 앉아 공책을 펴 둔 고양이",
    description: "햇빛이 드는 교실에서 주황색 고양이가 책상 앞 의자에 앉아 빈 공책과 연필꽂이를 앞에 둔 사진입니다. 학생처럼 보이는 자세와 텅 빈 공책의 대비를 살리면 공부와 시작에 얽힌 제목을 만들기 좋습니다.",
    alt: "햇빛 드는 교실의 나무 책상 앞 의자에 앉아 빈 공책과 색연필꽂이를 앞에 둔 주황색 고양이",
    prompt: "사람 학생의 책상에 앉은 고양이를 무엇을 배우러 온 학생처럼 상상해보세요.",
    observationPoints: ["책상 앞에 단정히 앉은 고양이", "펼쳐진 빈 공책과 연필 한 자루", "창으로 들어오는 따뜻한 햇빛과 교실 책장"],
    exampleTitles: ["오늘 첫 수업입니다", "제목 짓기 1교시", "아직 한 글자도 못 썼다"],
    isUserUpload: false,
  },
  {
    id: "imm-022",
    imageKey: "34",
    src: "assets/gallery/shore-crab-in-hand.jpg",
    webpSrc: "assets/gallery/webp/shore-crab-in-hand.webp",
    title: "바닷가에서 두 집게를 치켜든 게",
    description: "검은 바위가 이어진 해안에서 사람이 게의 배가 보이도록 손 위에 올려 든 사진입니다. 몸집보다 크게 벌린 두 집게와 붙잡힌 처지가 대비되어, 당당한 대사형 제목을 붙이기 좋습니다.",
    alt: "검은 바위 해안을 배경으로 사람 손 위에서 배를 보인 채 두 집게를 치켜든 게",
    prompt: "붙잡힌 상황에서도 두 집게를 높이 든 게가 어떤 말을 하고 있을지 짧은 대사로 상상해보세요.",
    observationPoints: ["좌우로 크게 치켜든 밝은색 집게", "손바닥 위로 드러난 게의 배와 여러 다리", "잔잔한 바다와 검은 바위 해안"],
    exampleTitles: ["잡힌 건 난데 항복은 네가 해", "두 집게 들었으니 덤벼", "오늘 해변의 최종 보스"],
    isUserUpload: false,
  },
  {
    id: "imm-023",
    imageKey: "35",
    src: "assets/gallery/giant-nose-side-eye.png",
    webpSrc: "assets/gallery/webp/giant-nose-side-eye.webp",
    title: "커다란 코 너머로 곁눈질하는 남자",
    description: "화면 대부분을 차지하는 커다란 코를 중심으로, 양옆 눈이 비스듬히 흐르고 입꼬리는 살짝 올라간 AI 생성 일러스트입니다. 과장된 얼굴 비율과 묘한 표정을 살려 눈치 보기나 딴생각을 담은 대사형 제목을 붙이기 좋습니다.",
    alt: "커다란 코가 화면 중앙을 가득 채우고 옆으로 곁눈질하며 살짝 웃는 남자의 AI 생성 일러스트",
    prompt: "화면을 가득 채운 코와 옆으로 흐르는 눈동자, 올라간 입꼬리를 단서로 들킨 순간의 속마음을 상상해보세요.",
    observationPoints: ["화면 중앙을 가득 채운 과장된 코", "양옆으로 비스듬히 흐르는 눈동자", "살짝 올라간 입꼬리와 턱의 짧은 수염"],
    exampleTitles: ["코앞인데 못 본 척", "나 안 봤는데", "눈치만 살짝 두고 갑니다"],
    sourceName: "사용자 제공 AI 생성 이미지",
    sourceUrl: "",
    author: "사용자 제공",
    license: "사용자가 사이트 게시를 위해 제공한 AI 생성 이미지",
    attributionRequired: false,
    commercialUseAllowed: false,
    modificationAllowed: false,
    publishedAt: "2026-07-15",
    updatedAt: "2026-07-15",
    isUserUpload: false,
  },
  {
    id: "imm-024",
    imageKey: "36",
    src: "assets/gallery/raincoat-duck-bus-stop.png",
    title: "비 오는 버스 정류장에서 함께 기다리는 여성과 오리",
    description: "비 내리는 저녁 버스 정류장에서 투명 우산을 든 정장 차림의 여성과 노란 우비를 입은 오리가 나란히 버스를 기다리는 듯 서 있는 AI 생성 사진입니다. 익숙한 퇴근길 풍경에 자연스럽게 섞인 뜻밖의 동행을 살리면 담담하면서도 재미있는 제목을 만들기 좋습니다.",
    alt: "비 오는 저녁 버스 정류장에서 투명 우산을 든 정장 차림의 여성 옆에 노란 우비를 입은 오리가 나란히 서 있는 모습",
    prompt: "평범한 퇴근길에 너무 자연스럽게 합류한 오리를 오래 알고 지낸 동행처럼 상상해보세요.",
    observationPoints: ["투명 우산을 들고 버스를 기다리는 정장 차림의 여성", "사람처럼 노란 우비를 입고 나란히 선 오리", "빗물에 불빛이 번지는 도로와 다가오는 버스"],
    exampleTitles: ["오늘도 같은 정류장", "퇴근길 동료가 조금 노랗다", "비 오는 날의 단골 승객"],
    sourceName: "제목 학원 AI 생성 이미지",
    sourceUrl: "https://jemokhakwon.com/about",
    author: "제목 학원",
    license: "사이트 내 제목 연습용으로 생성·검토된 이미지",
    attributionRequired: false,
    commercialUseAllowed: false,
    modificationAllowed: false,
    publishedAt: "2026-08-03",
    updatedAt: "2026-08-03",
    isUserUpload: false,
  },
];
